/**
**************************************************************************
* @file     mc_type.h
* @brief    Motor control data types and enumerations
**************************************************************************
*                       Copyright notice & Disclaimer
*
* The software Board Support Package (BSP) that is made available to
* download from Artery official website is the copyrighted work of Artery.
* Artery authorizes customers to use, copy, and distribute the BSP
* software and its related documentation for the purpose of design and
* development in conjunction with Artery microcontrollers. Use of the
* software is governed by this copyright notice and the following disclaimer.
*
* THIS SOFTWARE IS PROVIDED ON "AS IS" BASIS WITHOUT WARRANTIES,
* GUARANTEES OR REPRESENTATIONS OF ANY KIND. ARTERY EXPRESSLY DISCLAIMS,
* TO THE FULLEST EXTENT PERMITTED BY LAW, ALL EXPRESS, IMPLIED OR
* STATUTORY OR OTHER WARRANTIES, GUARANTEES OR REPRESENTATIONS,
* INCLUDING BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
*
**************************************************************************
*/

#ifndef __MC_TYPE_H
#define __MC_TYPE_H

#ifdef __cplusplus
extern "C" {
#endif


#include "mc_lib.h"

/**
  * @brief  Union for 32-bit/16-bit word conversion
  * @details Allows access to 32-bit data as either one long word or two 16-bit words
  */
typedef union
{
  int32_t long_word;          /**< Combined 32-bit signed integer */
  struct
  {
    int16_t low_word;         /**< Lower 16-bit portion (LSBs) */
    int16_t high_word;        /**< Upper 16-bit portion (MSBs) */
  };
} long_words_union;

/**
  * @brief  Float-uint32 union for type conversion
  */
typedef union
{
  float f;      /**< Floating-point representation */
  uint32_t u32; /**< Raw 32-bit unsigned integer representation */
} float_u32_union;

/**
 * @brief Enumeration defining different motor control algorithm types
 *
 * This enumeration identifies various motor control firmware types used in the system.
 * Each value represents a specific control algorithm and sensor configuration combination.
 */
typedef enum
{
  BLDC_HALL_SENSOR               = 0x00, /**< BLDC motor control using Hall sensors */
  BLDC_SENSOR_LESS_ADC           = 0x01, /**< Sensorless BLDC control using ADC measurements */
  BLDC_SENSOR_LESS_COMP          = 0x02, /**< Sensorless BLDC control using comparator */
  SPMSM_HALL_SENSOR              = 0x03, /**< Surface PMSM control using Hall sensors */
  SPMSM_ENCODER                  = 0x04, /**< Surface PMSM control using incremental encoder */
  SPMSM_SENSOR_LESS_OPEN_LOOP    = 0x05, /**< Sensorless Surface PMSM open-loop control */
  SPMSM_SENSOR_LESS_ALIGN_AND_GO = 0x06, /**< Sensorless Surface PMSM with align-and-go startup */
  SPMSM_SENSOR_LESS_ANGLE_INIT   = 0x07, /**< Sensorless Surface PMSM with angle initialization */
  SPMSM_ABS_ENCODER              = 0x08, /**< Surface PMSM control using absolute encoder */
  IPMSM_HALL_SENSOR              = 0x09, /**< Interior PMSM control using Hall sensors */
  IPMSM_ENCODER                  = 0x0A, /**< Interior PMSM control using incremental encoder */
  IPMSM_ABS_ENCODER              = 0x0B  /**< Interior PMSM control using absolute encoder */
} firmware_id_type;

/**
  * @brief  Enumeration defining different motor control modes
  */
typedef enum
{
  OPEN_LOOP_CTRL           = 0x00, /**< Open-loop control without feedback */
  VF_CTRL                  = 0x01, /**< Voltage-Frequency (V/f) control mode */
  ID_MANUAL_TUNE           = 0x02, /**< Manual tuning mode for d-axis current */
  IQ_MANUAL_TUNE           = 0x03, /**< Manual tuning mode for q-axis current */
  TORQUE_CTRL              = 0x04, /**< Torque control mode (q-axis current control) */
  SPEED_CTRL               = 0x05, /**< Closed-loop speed control mode */
  POSITION_CTRL            = 0x06, /**< Closed-loop position control mode */
} motor_control_mode;

/**
 * @brief Enumeration defining control command sources
 *
 * This enumeration specifies the origin of control commands for the motor drive system.
 * It distinguishes between software generated commands and external control inputs.
 */
typedef enum
{
  CTRL_SOURCE_SOFTWARE     = 0x00,  /**< Control commands generated by software */
  CTRL_SOURCE_EXTERNAL     = 0x01,  /**< Control commands received from external sources */
} ctrl_source_type;

/**
 * @brief Enumeration defining general calibration process states
 *
 * This enumeration represents the various stages and outcomes of system calibration procedures,
 * including but not limited to:
 * - Encoder alignment process
 * - Current loop PI parameter calibration
 * - Other system tuning procedures
 *
 * @note The state machine should handle transitions between these states appropriately
 *       for different calibration types.
 */
typedef enum
{
  UNDO                     = 0x00, /**< Calibration procedure has not been initiated (idle state) */
  PROCESSING               = 0x01, /**< Calibration procedure is actively running */
  FINISHED                 = 0x02, /**< Calibration completed without success/failure status
                                   (neutral completion state) */
  SUCCEED                  = 0x03, /**< Calibration completed successfully with verified results */
  FAILED                   = 0x04  /**< Calibration procedure failed due to error or timeout */
} process_state_type;

/**
  * @brief  controller state type definition
  *
  * This enumeration represents the complete state machine of the ESC controller,
  * including normal operation modes, initialization procedures, and special configurations
  */
typedef enum
{
  ESC_STATE_IDLE           = 0x00, /**< Initial idle state, motor stopped */
  ESC_STATE_SAFETY_READY   = 0x01, /**< Pre-operation checks completed, ready for initialization */
  ESC_STATE_ANGLE_INIT     = 0x02, /**< Initializing rotor angle position */
  ESC_STATE_STARTING       = 0x03, /**< Motor startup sequence in progress */
  ESC_STATE_RUNNING        = 0x04, /**< Normal closed-loop operation */
  ESC_STATE_FREE_RUN       = 0x05, /**< Freewheeling mode (no active braking) */
  ESC_STATE_BRAKING        = 0x06, /**< Active braking mode */
  ESC_STATE_ERROR          = 0x07, /**< Fault condition state (requires reset) */
#if defined INCREM_ENCODER || defined MAGNET_ENCODER_W_ABZ || defined MAGNET_ENCODER_WO_ABZ
  ESC_STATE_ENC_ALIGN      = 0x08, /**< Encoder alignment state */
#endif
  ESC_STATE_I_TUNE         = 0x09, /**< Current loop PI parameter tuning */
#ifdef E_BIKE_SCOOTER
  ESC_STATE_REVERSE_RUN    = 0x0A, /**< Reverse direction operation for e-bikes/scooters */
#endif
#ifdef MOTOR_PARAM_IDENTIFY
  ESC_STATE_WINDING_PARAM_ID  = 0x0B, /**< Motor winding parameter identification */
#endif
  ESC_STATE_AUTO_LEARN     = 0x0C, /**< Hall sensor auto-learning mode (automatic hall position calibration) */
#ifdef WIND_SENSE
  ESC_STATE_SPIN_CHECK     = 0x0D, /**< Motor rotation detection verification */
  ESC_STATE_HEADWIND_BRAKE = 0x0E, /**< Headwind braking operation */
  ESC_STATE_LOCK_MOTOR     = 0x0F, /**< Motor locking state before start-up */
#endif
#ifdef E_BIKE_SCOOTER
  ESC_STATE_ANTI_THEFT     = 0x10, /**< Anti-theft mode state for e-bikes/scooters */
  ESC_STATE_PARKING_LOCK   = 0x11, /**< Parking lock state for e-bikes/scooters */
#endif
  ESC_STATE_NONE           = 0x12  /**< Invalid/undefined state */
} esc_state_type;

/**
  * @brief  BLDC sensorless startup state machine
  */
typedef enum
{
  START_STATE_IDLE        = 0x00, /**< Initial standby state */
  START_STATE_FIRST_STEP  = 0x01, /**< First commutation step */
  START_STATE_SENSE_HALL  = 0x02, /**< Back-EMF sensing phase */
  START_STATE_STABLE_RUN  = 0x03, /**< Normal closed-loop operation */
} start_state_type;

/**
 * @brief Enumeration defining motor control system error codes
 *
 * This enumeration represents all possible fault conditions in the motor control system.
 * Error codes use bitmask values to allow reporting multiple simultaneous faults.
 * Each code represents a specific category of system malfunction or protection trigger.
 */
typedef enum
{
  MC_NO_ERROR              = 0x00,   /**< No active errors (normal operation) */
  MC_OVER_VOLT_ERROR       = 0x01,   /**< DC bus overvoltage protection triggered */
  MC_UNDER_VOLT_ERROR      = 0x02,   /**< DC bus undervoltage protection triggered */
  MC_OVER_TEMP_ERROR       = 0x04,   /**< Overtemperature condition detected */
  MC_OVER_CURRENT_ERROR    = 0x08,   /**< Overcurrent protection triggered */
  MC_ENCODER_ERROR         = 0x10,   /**< Encoder fault condition detected */
  MC_HALL_ERROR            = 0x20,   /**< Hall sensor fault detected */
  MC_PARAM_IDENT_ERROR     = 0x40,   /**< Motor parameter identification failure  */
  MC_HALL_LEARN_ERROR      = 0x80,   /**< Hall sensor auto-learning procedure failed */
  MC_STARTUP_ERROR         = 0x100,  /**< Motor startup sequence failure
                                      *   (failed to achieve stable open-to-closed loop transition) */
} err_code_type;

/**
  * @brief  current shunt number type definition
  */
typedef enum
{
  ONESHUNT                = 0x01,   /**< Single shunt configuration. */
  TWOSHUNT                = 0x02,   /**< Two-shunt configuration. */
  THREESHUNT              = 0x03    /**< Three-shunt configuration. */
} shunt_nbr_type;

/**
  * @brief  low speed control type definition
  */
typedef enum
{
  WITHOUT_CURR_CTRL         = 0x00,  /**< without current control */
  WITH_CURR_CTRL            = 0x01,  /**< with current control */
} low_spd_ctrl_type;

/**
 * @brief Defines the states of the Hall sensor self-learning process.
 *
 * This enumeration outlines the distinct stages of the automatic
 * learning procedure for a motor's Hall sensors. It guides the system
 * through a sequence of operations to determine the correct commutation
 * logic for the motor.
 */
typedef enum
{
  PROCESS_0_LOCK     = 0x00,
  /**< The initial state where the motor is held in a fixed position (locked). */
  PROCESS_1_FREE_RUN = 0x01,
  /**< The motor is free to run with no PWM output, remaining at a standstill. */
  PROCESS_2_OPENLOOP = 0x02,
  /**< A specific control voltage is applied in an open-loop configuration to start rotation. */
  PROCESS_3_LEARNING = 0x03,
  /**< The main learning phase where Hall sensor transitions are actively recorded. */
  PROCESS_4_FINISH   = 0x04,
  /**< The learning process has been completed successfully. */
  PROCESS_5_ERROR    = 0x05
                       /**< An error has occurred, and the learning process has failed. */
} hall_learn_process_type;

/**
  * @brief  PWM input calibration state machine
  * @details Defines the step-by-step process for calibrating PWM input ranges
  *          and calculating speed curve parameters for motor control
  */
typedef enum
{
  PROCESS_0_WAITING          = 0x00, /**< Initial idle state (waiting for calibration trigger) */
  PROCESS_1_CATCH_ZERO       = 0x01, /**< Calibration initialization state */
  PROCESS_2_CATCH_MAX        = 0x02, /**< Capturing maximum PWM width (full forward) */
  PROCESS_3_CATCH_ZERO       = 0x03, /**< Capturing neutral/zero PWM width */
  PROCESS_4_CATCH_MIN        = 0x04, /**< Capturing minimum PWM width (full reverse) */
  PROCESS_5_CATCH_ZERO       = 0x05, /**< Final neutral/zero position verification */
  PROCESS_6_SUCCESS          = 0x06  /**< Calibration completed successfully */
} calibrate_process_type;

/**
  * @brief  Motor control mode definitions
  * @details Specifies different PWM input response modes for motor operation
  */
typedef enum
{
  MODE_FORWARD_REVERSE        = 0x00, /**< Mode 1: Basic forward/reverse */
  MODE_FORWARD_BRAKE          = 0x01, /**< Mode 2: Forward with braking */
  MODE_FORWARD_BRAKE_REVERSE  = 0x02, /**< Mode 3: Forward/brake/reverse with transition braking */
} switch_mode_type;

/**
  * @brief  Magnetic encoder calibration state machine
  * @details Defines the step-by-step process for calibrating encoder angles
  *          through controlled motor rotation and position locking
  */
typedef enum
{
  PROCESS_0_UNDO              = 0x00, /**< Initial state (calibration not started) */
  PROCESS_1_ALIGN             = 0x01, /**< Motor alignment phase (establish initial position) */
  PROCESS_2_CW_CLIBRATION     = 0x02, /**< Clockwise rotation calibration (forward direction) */
  PROCESS_3_LOCK              = 0x03, /**< Position hold phase (stabilize at end position) */
  PROCESS_4_CCW_CALIBRATION   = 0x04, /**< Counter-clockwise rotation calibration (reverse direction) */
  PROCESS_5_FINISH            = 0x05, /**< Calibration completed successfully */
  PROCESS_6_ERROR             = 0x06  /**< Error state (calibration failed) */
} encoder_calibrate_process_type;

/**
  * @brief  Constant voltage or current startup type definition (FOC control)
  */
typedef enum
{
  CONST_CURR_START           = 0x00, /**< constant current startup */
  CONST_VOLT_START           = 0x01  /**< constant voltage startup */
} startup_mode_type;

/**
  * @brief  current sensing of initial angle type definition(BLDC sensorless)
  */
typedef struct
{
  int16_t ab; /**< @brief Current measurement between Phase A and Phase B. */
  int16_t ac; /**< @brief Current measurement between Phase A and Phase C. */
  int16_t ba; /**< @brief Current measurement between Phase B and Phase A. */
  int16_t bc; /**< @brief Current measurement between Phase B and Phase C. */
  int16_t ca; /**< @brief Current measurement between Phase C and Phase A. */
  int16_t cb; /**< @brief Current measurement between Phase C and Phase B. */
} init_current_type;

/**
 * @brief Structure for initial angle estimation parameters in sensorless BLDC motor control.
 *
 * This structure encapsulates all the necessary parameters and state variables
 * required for the robust and accurate initial rotor angle estimation
 * in a sensorless Brushless DC (BLDC) motor drive. It integrates timer configurations,
 * measurement duty cycles, step counters, current feedback, and calculated differences
 * to establish the motor's starting position without physical sensors.
 */
typedef struct
{
  tmr_type* ADVTMRx;       /**< @brief Pointer to the advanced timer used for PWM generation and commutation control. */
  tmr_type* ADC_TMRx;      /**< @brief Pointer to the timer triggering Analog-to-Digital Converter (ADC) measurements. */
  uint16_t tmr_period;     /**< @brief The period of the main timer, typically dictating the PWM frequency. */
  uint16_t detect_duty;    /**< @brief The duty cycle used during the initial angle detection phase. */
  int16_t step_count;      /**< @brief Counter for the steps or phases in the initial angle detection sequence. */
  init_current_type current; /**< @brief Structure holding the phase-to-phase current measurements during detection. */
  int16_t difference;      /**< @brief Calculated difference used for angle determination. */
} angle_init_type;

/**
  * @brief  d/q-axis current/voltage components structure
  * @details Represents rotating reference frame quantities for FOC control
  */
typedef struct
{
  int16_t q;  /**< @brief Quadrature-axis component (torque-producing) */
  int16_t d;  /**< @brief Direct-axis component (flux-producing) */
} qd_type;

/**
  * @brief  3-phase current/voltage components structure
  * @details Represents stationary reference frame quantities for motor control
  */
typedef struct
{
  int16_t a;  /**< @brief Phase A component */
  int16_t b;  /**< @brief Phase B component */
  int16_t c;  /**< @brief Phase C component */
} abc_type;

/**
  * @brief  α/β-axis stationary reference frame structure
  * @details Represents Clarke transform outputs for FOC control
  */
typedef struct
{
  int16_t alpha;  /**< @brief α-axis component (Clarke transform output) */
  int16_t beta;   /**< @brief β-axis component (Clarke transform output) */
} alphabeta_type;

/**
  * @brief  Current sensor offset calibration structure
  * @details Stores ADC offset values for current sensing channels
  */
typedef struct
{
  uint16_t a;   /**< @brief Phase A current sensor offset (ADC value) */
  uint16_t b;   /**< @brief Phase B current sensor offset (ADC value) */
  uint16_t c;   /**< @brief Phase C current sensor offset (ADC value) */
  uint16_t bus; /**< @brief DC bus voltage sensor offset (ADC value) */
} curr_offs_type;

/**
  * @brief  DC bus current control structure for BLDC motor
  * @details Manages current regulation in BLDC drives
  */
typedef struct
{
  int16_t Ireal_pu;     /**< @brief Measured bus current (Q15 format) */
  int16_t Iref;         /**< @brief Current reference value */
  int16_t Istart;       /**< @brief Startup current */
  int16_t Icalc;        /**< @brief Calculated current for control */
  int16_t decay_const;  /**< @brief Current decay time constant */
} i_bus_type;

/**
  * @brief  DC current measurement structure for FOC
  * @details Handles DC bus current sensing in Field-Oriented Control
  */
typedef struct
{
  int16_t val;      /**< @brief Raw current measurement (ADC value) */
  int16_t filtered; /**< @brief Low-pass filtered current (ADC value) */
  int16_t offset;   /**< @brief Calibration offset (ADC value) */
} i_dc_type;

/**
  * @brief  Trigonometric components structure
  * @details Stores cosine/sine values for Park/Clarke transforms
  */
typedef struct
{
  int16_t cos_value;  /**< @brief Cosine value (Q15 format) */
  int16_t sin_value;  /**< @brief Sine value (Q15 format) */
} trig_components_type;

/**
 * @brief Current type definition
 *
 * This structure encapsulates various current measurements, transformations,
 * and related parameters essential for motor control applications.
 * It includes raw phase currents, their transformed components (alpha-beta, d-q),
 * current offsets, ADC configuration, and other calibration/limit values.
 */
typedef struct
{
  i_bus_type Ibus;                    /**< @brief DC bus current. */
  abc_type Iabc;                      /**< @brief Three-phase currents (Ia, Ib, Ic). */
  abc_type Iabc_shunt;                /**< @brief Three-phase currents measured via shunt resistors. */
  alphabeta_type Ialphabeta;          /**< @brief Alpha-beta components of the current (Clarke transformation). */
  qd_type Iqd;                        /**< @brief Direct-quadrature (d-q) components of the current (Park transformation). */
  qd_type Iqdref;                     /**< @brief Reference d-q current components. */
  qd_type Iqd_LPF;                    /**< @brief Low-pass filtered d-q current components. */
  curr_offs_type offset;              /**< @brief Current measurement offsets for calibration. */
  adc_type* ADCx;                     /**< @brief Pointer to the primary ADC instance for current sampling. */
  adc_type* ADC2x;                    /**< @brief Pointer to the secondary ADC instance for current sampling (if applicable). */
  adc_sampletime_select_type adc_sampletime; /**< @brief ADC sampling time configuration. */
  uint16_t span;                      /**< @brief Current measurement span or range. */
  uint16_t dc_span;                   /**< @brief DC current measurement span or range. */
  uint8_t span_shift;                 /**< @brief Bit shift value related to current span scaling. */
  int16_t nominal;                    /**< @brief Nominal current value. */
  int16_t max_current;                /**< @brief Maximum allowed current limit. */
  int16_t min_current;                /**< @brief Minimum allowed current limit. */
  int16_t volt_sign;                  /**< @brief Sign indicator for voltage, possibly related to current direction. */
  int16_t volt_sign_coming;           /**< @brief Pending sign indicator for voltage. */
  i_dc_type Idc;                      /**< @brief DC current measurement. */
  int16_t ID_1shunt;                  /**< @brief Direct current component when using a single shunt resistor measurement. */
  int16_t Isref;                      /**< @brief Reference stator current. */
  int32_t Iqd_squr_sum_max;           /**< @brief Maximum allowed sum of squared d-q currents (for current limit calculations). */
  int16_t Tref;                       /**< @brief Reference temperature, possibly for current derating. */
  tmr_type* adc_TMRx;                 /**< @brief Pointer to the timer instance controlling ADC triggering. */
  tmr_channel_select_type adc_tmr_trig_ch; /**< @brief Timer channel used for ADC trigger signal. */
  int16_t adc_trig_normal;            /**< @brief Normal ADC trigger point. */
  int16_t adc_trig_lagging;           /**< @brief Lagging ADC trigger point. */
} current_type;

/**
 * @brief Voltage type definition for Field-Oriented Control (FOC)
 * @details Structure containing all voltage-related parameters and intermediate values
 *          used in FOC algorithm implementation
 * 
 * This structure stores voltage components in different reference frames and
 * related control parameters for proper FOC operation and modulation management.
 */
typedef struct
{
  alphabeta_type   Valphabeta;          /**< Voltage vector in alpha-beta stationary reference frame */
  qd_type          Vqd;                 /**< Voltage vector in quadrature-direct rotating reference frame */
  qd_type          Vqd_filtered;        /**< Filtered voltage vector in q-d reference frame */
  int32_t          Vqd_squr_sum;        /**< Sum of squared q and d voltage components (Vq² + Vd²) */
  int32_t          Vqd_squr_sum_max;    /**< Maximum allowed sum of squared voltage components */
  int16_t          Vq_max;              /**< Maximum quadrature voltage limit */
  int16_t          Vd_max;              /**< Maximum direct voltage limit */
  uint8_t          sector;              /**< Current sector in space vector modulation */
  uint8_t          sector_old;          /**< Previous sector in space vector modulation */
  uint16_t         over_modulation_count; /**< Counter for over-modulation occurrences */
  uint16_t         om_max_count;        /**< Maximum allowed over-modulation count threshold */
} voltage_type;

/**
 * @brief ADC trigger position type definition for Field-Oriented Control (FOC)
 * @details Structure containing ADC sampling trigger positions within PWM period
 * 
 * This structure defines the timing positions for ADC sampling triggers used in FOC algorithm.
 * Proper ADC sampling timing is critical for accurate current measurement and control loop execution.
 */
typedef struct
{
  uint16_t          first_pos;       /**< First ADC sampling trigger position within PWM period */
  uint16_t          second_pos[2];   /**< Array of second ADC sampling trigger positions  */
  uint16_t          second_temp;     /**< Temporary storage for second trigger position calculation */
} adc_trigger_type;

/**
 * @brief PWM duty type definition for Field-Oriented Control (FOC)
 * @details Structure containing PWM duty cycle parameters and related timer configurations
 * 
 * This structure manages all PWM-related parameters including duty cycle values,
 * timer instances for PWM generation and ADC triggering, and various duty cycle
 * thresholds for proper motor control operation.
 */
typedef struct
{
  tmr_type*          ADVTMRx;              /**< Pointer to advanced timer instance for PWM generation */
  tmr_type*          SYNC_TMRx;            /**< Pointer to synchronization timer instance */
  tmr_type*          adc_TMRx;             /**< Pointer to the timer instance controlling ADC triggering */
  tmr_channel_select_type adc_tmr_trig_ch; /**< Timer channel used for ADC trigger signal */
  abc_type           OF;                   /**< Rising part duty cycle values for three phases */
  abc_type           UF;                   /**< Falling part duty cycle values for three phases */
  int16_t            duty_buffer[6];       /**< Buffer storing duty cycle values for PWM updates */
  adc_trigger_type   adc_trig;             /**< ADC trigger positions configuration */
  uint16_t           half_duty;            /**< Half of pwm period value */
  uint16_t           double_duty;          /**< Double of pwm period value */
  uint16_t           quarter_duty;         /**< Quarter of maximum duty cycle value */
  uint16_t           threshold;            /**< Pwm period threshold for current sampling channel seletion */
  int16_t            min_interval;         /**< Minimum interval between PWM updates */
} pwm_duty_type;

/**
  * @brief  PID Controller Configuration and Runtime Structure
  * @details Implements a full-featured fixed-point PID controller with:
  *          - Anti-windup protection
  *          - Gain scheduling
  *          - Fractional coefficient scaling
  *          - Output clamping
  *          Suitable for motor control and motion applications.
  */
typedef struct
{
  int16_t kp_gain;        /**< @brief Proportional gain (Q15 format) */
  int16_t ki_gain;        /**< @brief Integral gain (Q15 format) */
  int16_t kd_gain;        /**< @brief Derivative gain (Q15 format) */

  int32_t upper_limit_integral;  /**< @brief Maximum accumulated integral value */
  int32_t lower_limit_integral;  /**< @brief Minimum accumulated integral value */
  int16_t upper_limit_output;    /**< @brief Maximum controller output value */
  int16_t lower_limit_output;    /**< @brief Minimum controller output value */

  int32_t integral;      /**< @brief Current integral accumulator */
  int32_t error;         /**< @brief Current control error */
  int32_t pre_error;     /**< @brief Previous control error (for derivative term) */

  uint16_t kp_shift;     /**< @brief Right-shift bits for P term scaling */
  uint16_t ki_shift;     /**< @brief Right-shift bits for I term scaling */
  uint16_t kd_shift;     /**< @brief Right-shift bits for D term scaling */

  int16_t ki_gain_1st;   /**< @brief First integral gain (for position-control) */
  int16_t ki_gain_2nd;   /**< @brief Secondary integral gain (for position-control) */
  int32_t out_start;     /**< @brief Stores unclamped PID output */
} pid_ctrl_type;

/**
  * @brief  pid controller function type definition
  * @details Fixed-point implementation with anti-windup and saturation
  */
typedef struct
{
  int16_t kp_gain;            /**< Proportional gain (Q15 format) */
  int16_t ki_gain;            /**< Integral gain (Q15 format) */
  int16_t kd_gain;            /**< Derivative gain (Q15 format) */
  int16_t upper_limit_output; /**< Output upper limit (anti-windup) */
  int16_t lower_limit_output; /**< Output lower limit (anti-windup) */
  int32_t error;              /**< Current control error */
  int32_t pre_error;          /**< Previous control error (for derivative) */
  uint16_t shift;             /**< Bit-shift for fixed-point scaling */
  long_words_union integral;  /**< Integrated error (32-bit with 16-bit access) */
} pid_ctrl_dc_type;

/**
 * @brief Rotor angle type definition for Field-Oriented Control (FOC)
 * @details Structure containing rotor angle information in both electrical and mechanical domains
 * 
 * This structure stores the current and previous rotor angle values used for
 * position estimation and control in FOC algorithms. Maintaining both electrical
 * and mechanical angles is essential for proper motor control and field orientation.
 */
typedef struct
{
  int16_t elec_angle_val;        /**< Current electrical angle of the rotor (0-32767 Q15 format) */
  int16_t elec_angle_pre_val;    /**< Previous electrical angle of the rotor (0-32767 Q15 format) */
  int16_t mech_anlge_val;        /**< Current rotation cycles (accumulated over multiple revolutions) */
} rotor_angle_type;

/**
 * @brief Encoder function type definition for Field-Oriented Control (FOC)
 * @details Structure containing all encoder-related parameters, states, and calibration data
 * 
 * This comprehensive structure manages encoder operation including position tracking,
 * speed calculation, alignment procedures, calibration processes, and hardware interface
 * configurations for accurate rotor position feedback in FOC systems.
 */
typedef struct
{
  int32_t count;                          /**< Current encoder count value (raw position) */
  int32_t pre_count;                      /**< Previous encoder count value (for delta calculation) */
  int32_t offset;                         /**< Encoder count offset for zero position calibration */
  int32_t val;                            /**< Processed encoder value after offset adjustment */
  int32_t delta;                          /**< Difference between current and previous count (for speed calculation) */
  int16_t stop_counter;                   /**< Counter for detecting motor stop condition */
  process_state_type align;               /**< Encoder alignment process state */
  process_state_type calibrate;           /**< Encoder calibration process state */
  confirm_state idx_reset_flag;           /**< Index signal reset confirmation flag */
  tmr_type* TMRx;                         /**< Pointer to timer instance for encoder interface */
  tmr_type* TMRx_Cap;                     /**< Pointer to timer instance for capture functionality */
  exint_type* EXINTx;                     /**< Pointer to external interrupt controller for index signal */
  uint32_t ext_z_line;                    /**< External index signal line configuration */
  int32_t cpr_nbr;                        /**< Counts Per Revolution (encoder resolution) */
  int32_t half_cpr_nbr;                   /**< Half of CPR value */
  uint32_t align_time;                    /**< Time duration for alignment procedure */
  uint32_t mech_to_elect_angle;           /**< Mechanical to electrical angle conversion factor */
  uint8_t mech_to_elect_angle_shift;      /**< Bit shift value for angle conversion optimization */
  float cpr_to_rpm;                       /**< Conversion factor from CPR to RPM */
  uint16_t stall_time;                    /**< Time threshold for stall detection */
  uint8_t pole_pairs;                     /**< Number of motor pole pairs */
  qd_type volt;                           /**< Voltage applied during encoder aligment process */
  uint8_t spd_period_count;               /**< Counter for speed calculation period when delta equals zero */
  uint32_t const_timer_clks;              /**< Constant timer clock counts for speed calculation period */
  uint32_t est_speed_const;               /**< Constant for speed estimation calculation */
  int16_t index_count;                    /**< Index signal width gap between A and B signals(counts) */
  uint16_t calibrate_count;               /**< Counter for angle calibration procedure */
  encoder_calibrate_process_type calibrate_state; /**< Current state of encoder calibration process */
  flag_status calibrate_flag;             /**< Flag indicating calibration status */
  int16_t calibrate_volt;                 /**< Voltage applied during angle calibration procedure */
} encoder_type;

/**
  * @brief  Open-loop control structure for FOC
  * @details Used for initial motor startup and encoder calibration
  */
typedef struct
{
  int16_t theta;      /**< Current electrical angle (0-32767 Q15 format) */
  int16_t inc;        /**< Angle increment per control cycle (speed control) */
  qd_type volt;       /**< Q/D-axis voltage commands (Vq = torque, Vd = flux) */
} open_loop_type;

/**
  * @brief BLDC motor open-loop control configuration structure
  * @details This structure contains all parameters required for open-loop control
  *          of a BLDC motor. It includes initialization values, ramp-up parameters,
  *          and final operation values.
  */
typedef struct
{
  int16_t olc_count;          /**< @brief Current step counter for open-loop control */
  int16_t volt_ref;           /**< @brief Current voltage reference value (Q format) */
  int16_t period_ref;         /**< @brief Current commutation period reference (PWM cycles) */

  int16_t olc_init_volt;      /**< @brief Initial voltage for motor startup (Q format) */
  int16_t olc_init_spd;       /**< @brief Initial speed reference (RPM) */
  int16_t olc_init_period;    /**< @brief Initial commutation period (in timer ticks) */

  int16_t olc_volt_inc;       /**< @brief Voltage increment per step during ramp-up (Q format) */
  int16_t olc_period_dec;     /**< @brief Period decrement per step during ramp-up (PWM cycles) */
  int16_t olc_times;          /**< @brief Total number of steps for open-loop acceleration */

  int16_t olc_final_spd;      /**< @brief Target speed after open-loop acceleration (RPM) */
  int16_t olc_final_period;   /**< @brief Target commutation period after acceleration (PWM cycles) */
} olc_type;

/**
  * @brief  Motor speed measurement and processing structure
  * @details This structure contains all parameters required for speed measurement,
  *          filtering, and direction detection for a motor control system.
  */
typedef struct
{
  int32_t val;                /**< @brief Raw speed value (RPM) */
  int32_t filtered;           /**< @brief Filtered speed value after processing (RPM) */
  int8_t dir;                 /**< @brief Movement direction(BLDC:forward=1,reverse=0/FOC:forward=1,reverse=-1) */
  uint16_t shift;             /**< @brief Bit shift value used for filtering calculations */
  int32_t val_temp;           /**< @brief Temporary storage for intermediate speed calculations */
  uint32_t speed_count;       /**< @brief Counter for speed measurement pulses or timer captures */
  long_words_union interval_filter; /**< @brief Filtered time interval measurement between speed pulses */
} speed_type;

/**
  * @brief  Generic value storage and filtering structure
  * @details This structure provides a way to store current, filtered, and previous values
  *          of a signal or measurement, commonly used for signal processing in control systems.
  */
typedef struct
{
  int16_t val;        /**< @brief Current raw value of the signal or measurement */
  int16_t filtered;   /**< @brief Filtered version of the value (after processing or smoothing) */
  int16_t old;        /**< @brief Previous value (typically used for delta calculations or filters) */
} value_type;

/**
  * @brief  Hall sensor processing and commutation control structure
  * @details This structure contains all parameters required for hall sensor decoding,
  *          speed measurement, and position estimation for BLDC motor control.
  */
typedef struct
{
  uint8_t state;               /**< @brief Current hall sensor state (bitmask of H1-H3) */
  uint8_t pre_state;           /**< @brief Previous hall sensor state (for edge detection) */
  uint8_t next_state;          /**< @brief Predicted next state (for commutation advance) */

  int32_t offset;              /**< @brief Angular offset compensation (in control units) */
  uint32_t hall_interval;      /**< @brief Raw time between hall sensor edges (in timer ticks) */
  uint32_t hall_interval_filt; /**< @brief Filtered hall sensor interval (for speed calculation) */
  uint32_t double_interval;    /**< @brief Double interval measurement (for low-speed detection) */

  int16_t theta_inc;           /**< @brief Angle increment per control cycle (for position estimation) */
  int32_t theta_cmpsat;        /**< @brief Computed angle value (in control units) */
  int16_t slick_speed;         /**< @brief Computed speed value (filtered, in RPM) */
  int16_t max_angle_err;       /**< @brief Maximum allowable angle error (for fault detection) */

  /** @brief Hardware abstraction group */
  gpio_type* H1_port;          /**< @brief GPIO port for Hall sensor 1 */
  gpio_type* H2_port;          /**< @brief GPIO port for Hall sensor 2 */
  gpio_type* H3_port;          /**< @brief GPIO port for Hall sensor 3 */
  uint32_t  H1_pin;            /**< @brief Pin number for Hall sensor 1 */
  uint32_t  H2_pin;            /**< @brief Pin number for Hall sensor 2 */
  uint32_t  H3_pin;            /**< @brief Pin number for Hall sensor 3 */
} hall_sensor_type;

/**
  * @brief  Back-EMF sampling configuration structure (BLDC sensorless)
  * @details Contains parameters for zero-crossing detection and sampling timing
  *          in sensorless BLDC motor control using back-EMF sensing.
  */
typedef struct
{
  tmr_type *read_emf_tmr_x;       /**< @brief Timer used for EMF sampling timing */

  /** @brief Low-speed sampling parameters */
  int16_t emf_low_spd_sample_point; /**< @brief Phase angle point (in timer ticks) for low-speed sampling */
  int16_t emf_change_duty_low;      /**< @brief PWM duty threshold for low-speed mode transition(in timer ticks) */

  /** @brief High-speed sampling parameters */
  int16_t emf_change_duty_high;        /**< @brief PWM duty threshold for high-speed mode transition(in timer ticks) */
  int16_t emf_high_spd_offset_rising;  /**< @brief Timing offset for rising edge detection (in Voltage ADC conversion value) */
  int16_t emf_high_spd_offset_falling; /**< @brief Timing offset for falling edge detection (in Voltage ADC conversion value) */

  /** @brief Voltage threshold parameters */
  int16_t emf_half_vdc_val;         /**< @brief Half DC-bus voltage threshold for zero-crossing detection(in Voltage ADC conversion value) */

  /** @brief Noise handling parameters */
  uint16_t emf_high_spd_sample_cnt; /**< @brief Number of consecutive samples required for validation */
  int16_t emf_avoid_noise_times;    /**< @brief Noise immunity filter threshold (sample cycles to ignore) */

  /** @brief Hardware configuration flags */
  flag_status emf_pull_up;             /**< @brief Enable/disable internal pull-up for EMF sensing */
  flag_status emf_comp_continous_mode; /**< @brief Enable continuous comparator mode (vs sampled mode) */
} emf_sample_type;

/**
  * @brief  ADC sampling configuration structure (BLDC sensorless)
  * @details Contains parameters for current and back-EMF sampling timing,
  *          hardware configuration, and voltage reference calibration
  *          in sensorless BLDC motor control systems.
  */
typedef struct
{
  tmr_type* ADVTMRx;              /**< @brief Advanced timer for PWM generation and triggering */
  tmr_type* ADC_TMRx;             /**< @brief Dedicated timer for ADC sampling synchronization */
  tmr_type *change_phase_tmr_x;   /**< @brief Timer used for phase commutation timing */
  adc_type *adc_x;                /**< @brief ADC peripheral used for measurements */
  int16_t i_sample_min_cnt;       /**< @brief Minimum count between current samples */
  int16_t i_sample_delay_count;   /**< @brief Delay count for current sampling (in timer ticks) */
  int16_t current_sampling_point; /**< @brief Optimal sample point for current sampling  */
  int16_t emf_sampling_point;     /**< @brief Optimal sample point for back-EMF zero-crossing detection */
  int16_t adc_sample_point[2][3]; /**< @brief Matrix storing ADC sampling points */
  int16_t adc_sample_page;        /**< @brief Active sample buffer page index (0 or 1) */
  int16_t vref_cal_ratio;         /**< @brief Internal voltage reference calibration ratio */
  emf_sample_type emf;            /**< @brief Back-EMF detection parameters */
} adc_sample_type;

/**
  * @brief  Ramp command generator structure
  * @details Provides smooth acceleration/deceleration profiling for motor control commands
  *          using configurable slope parameters. Typically used for speed ramping.
  */
typedef struct
{
  int32_t cmd_final;    /**< @brief Target command value (final setpoint in RPM) */
  int32_t command;      /**< @brief Current output command (ramped value in RPM) */
  int16_t acc_slope;    /**< @brief Acceleration slope (increment per control cycle) */
  int16_t dec_slope;    /**< @brief Deceleration slope (decrement per control cycle) */
} ramp_cmd_type;

/**
 * @brief Position controller function type definition
 * @details Structure containing parameters and states for position control loop
 * 
 * This structure manages all aspects of position control including command processing,
 * error calculation, speed profiling, and stability monitoring for precise motor positioning.
 */
typedef struct
{
  int32_t cmd_new;                /**< New position command input */
  int32_t cmd_final;              /**< Final processed position command */
  int32_t command;                /**< S-curve position command */
  int32_t val;                    /**< Actual measured position value */
  int32_t error;                  /**< Position error (cmd_final - S-curve command) */
  uint8_t count;                  /**< Control loop counter */
  int32_t spd_cmd;                /**< Speed command derived from S-curve position control */
  int16_t spd_slope;              /**< Speed slope for acceleration/deceleration profiling */
  int16_t spd_slope_ratio;        /**< Ratio for speed slope adjustment */
  int16_t cmd_to_val_gap;         /**< Maximum allowable gap between command and actual position */
  int16_t small_pos_cmd_gap;      /**< Threshold for small position command detection */
  int16_t min_pos_ctrl_spd;       /**< Minimum speed for position control operation */
  flag_status brake_flag;         /**< Brake engagement flag */
  confirm_state stable;           /**< Position stability confirmation state */
  float rpm_to_cpr;               /**< Conversion factor from RPM to counts per revolution */
} position_type;

/**
  * @brief  Mechanical angle type definition for FOC (Field-Oriented Control)
  * @note   All values are in units of degree/100 (0.01 degree resolution)
  */
typedef struct
{
  int32_t cmd_final;              /**< Final processed position command in degree/100 units */
  int32_t command;                /**< S-curve profiled position command in degree/100 units */
  int32_t val;                    /**< Actual measured mechanical angle value in degree/100 units */
} angle_type;

/**
  * @brief  USART frame status structure
  */
typedef struct
{
  uint16_t  data_len;      /**< @brief Total received bytes (including protocol overhead) = buffer_size - DMA_remaining_count */
  uint16_t  frame_len;     /**< @brief Payload length = data_len - 3 (start byte + length byte + checksum) */
  uint16_t  no_error;      /**< @brief Frame validation flag (0=error, 1=valid) */
} usart_data_index;

/**
  * @brief  Moving average filter structure
  * @details Implements a configurable moving average (rolling/running average) filter
  *          for signal processing applications. Supports both integer and fixed-point arithmetic.
  */
typedef struct
{
  uint16_t order;      /**< @brief Filter order */
  uint16_t index;      /**< @brief Current position in circular buffer */
  uint16_t full_flag;  /**< @brief Buffer fill status (0=not full, 1=fully populated) */
  uint16_t shift;      /**< @brief Right-shift value for division (for power-of-2 window sizes) */
  int32_t  sum;        /**< @brief Sum of values in the buffer */
  int32_t* buffer;     /**< @brief Pointer to dynamically allocated circular buffer */
} moving_average_type;

/**
  * @brief  Field weakening function type definition
  * @note   This structure contains parameters and variables for field weakening control
  */
typedef struct
{
  pid_ctrl_type pid_fw;           /**< PID controller for field weakening regulation */
  int16_t Id_max;                 /**< Maximum allowable D-axis current for field weakening */
  int32_t fw_err_filt;            /**< Filtered field weakening error signal */
} field_weakening_type;

/**
  * @brief  Low-pass filter structure
  */
typedef struct
{
  int32_t sample_freq;    /**< @brief Sampling frequency in Hz */
  int16_t bandwidth;      /**< @brief Cutoff frequency in rad/s (-3dB point) */
  int16_t coef1;          /**< @brief Input coefficient (Q15 format) */
  int16_t coef2;          /**< @brief Feedback coefficient (Q15 format) */
  int64_t output_temp;    /**< @brief 64-bit accumulator for calculations */
  int32_t residual;       /**< @brief Residual value for precision */
} lowpass_filter_type;

/**
 * @brief Motor voltage data structure for FOC sensorless control
 * 
 * This structure contains voltage-related parameters and measurements used in 
 * Field-Oriented Control (FOC) without position sensors. It stores both 
 * calculated alpha-beta components and actual phase voltage measurements.
 */
typedef struct
{
  alphabeta_type* Valphabeta;      /**< Pointer to calculated alpha-beta voltage components */
  alphabeta_type* Ialphabeta;      /**< Pointer to measured alpha-beta current components */
  __IO uint16_t* Vbus;             /**< Pointer to DC bus voltage measurement */
  __IO uint16_t* Va;               /**< Pointer to phase A voltage measurement */
  __IO uint16_t* Vb;               /**< Pointer to phase B voltage measurement */
  __IO uint16_t* Vc;               /**< Pointer to phase C voltage measurement */
  int16_t emf_factor;              /**< Back-EMF compensation factor for scales back-EMF measurement based on bus voltage sensing */
  alphabeta_type Vpu;              /**< Per-unit voltage values in alpha-beta reference frame */
} motor_volt_type;

/**
 * @brief Back-EMF voltage data structure for FOC sensorless control
 * 
 * This structure contains back-electromotive force (EMF) related parameters
 * used for position and speed estimation in sensorless Field-Oriented Control.
 * It stores EMF measurements in multiple reference frames and filtering data.
 */
typedef struct
{
  abc_type emf_abc_voltage;           /**< Back-EMF voltage values in three-phase ABC reference frame */
  abc_type emf_abc_offset;            /**< Offset compensation values for ABC phase EMF measurements */
  alphabeta_type emf_alphabeta_voltage; /**< Back-EMF voltage values in alpha-beta reference frame */
  uint32_t time_count;                /**< Time counter for EMF measurement and estimation timing */
  int16_t max_bemf_val;               /**< Maximum back-EMF amplitude value (raw measurement) */
  int16_t max_bemf_val_filt;          /**< Filtered maximum back-EMF amplitude value for stable estimation */
} motor_emf_type;

/**
 * @brief State observer structure for FOC sensorless control
 * 
 * This structure implements a state observer (Luenberger observer)
 * for sensorless Field-Oriented Control. It estimates motor states including back-EMF,
 * current, electrical angle, and speed without using physical position sensors.
 */
typedef struct
{
  float *Rs;                          /**< Pointer to stator resistance value (Ω) */
  float *Ls;                          /**< Pointer to stator inductance value (H) */
  int16_t c1;                         /**< Observer coefficient 1 for state estimation */
  int32_t c2;                         /**< Observer coefficient 2 for state estimation */
  int32_t c3;                         /**< Observer coefficient 3 for state estimation */
  int16_t c4;                         /**< Observer coefficient 4 for state estimation */
  int32_t c5;                         /**< Observer coefficient 5 for state estimation */
  int32_t wIalpha_est;                /**< Estimated alpha-axis current (Q32-format) */
  int32_t wIbeta_est;                 /**< Estimated beta-axis current (Q32-format) */
  int16_t hIalpha_est;                /**< Estimated alpha-axis current (Q16-format) */
  int16_t hIbeta_est;                 /**< Estimated beta-axis current (Q16-format)*/
  int32_t wBemf_alpha_est;            /**< Estimated alpha-axis back-EMF (Q32-format) */
  int32_t wBemf_beta_est;             /**< Estimated beta-axis back-EMF (Q32-format) */
  int16_t hBemf_alpha_est;            /**< Estimated alpha-axis back-EMF (Q16-format) */
  int16_t hBemf_beta_est;             /**< Estimated beta-axis back-EMF (Q16-format) */
  int16_t elec_angle;                 /**< Estimated electrical angle (0-32767 represents 0-360°) */
  int8_t* dir;                        /**< Pointer to rotation direction (1 = forward, -1 = reverse) */
  speed_type motor_speed;             /**< Motor speed estimation data structure */
  int32_t elec_spd_to_rpm;            /**< Conversion factor from electrical speed to RPM */
  pid_ctrl_type pid_pll;              /**< PLL (Phase-Locked Loop) PID controller for speed/angle tracking */
} state_observer_type;

/**
 * @brief Sensorless startup control structure for FOC sensorless operation
 * 
 * This structure manages the startup sequence for sensorless Field-Oriented Control,
 * handling the transition from standstill to closed-loop operation without position sensors.
 * It includes open-loop startup parameters, alignment control, and closed-loop readiness flags.
 */
typedef struct
{
  int16_t max_speed;                  /**< Maximum speed limit during startup (RPM) */
  int16_t start_volt;                 /**< Constant voltage applied during startup */
  int16_t ol_angle;                   /**< Open-loop angle increment for forced rotation */
  uint16_t ol_delay_count;            /**< Delay counter for open-loop angle increments */
  uint16_t elec_spd_to_rpm;           /**< Conversion factor from electrical speed to RPM */
  uint32_t align_count;               /**< Alignment phase duration counter */
  uint32_t start_count;               /**< Startup phase duration counter after rotor aligment or initial angle detection */
  int16_t start_current;              /**< Constant current applied during startup */
  int16_t elec_angle;                 /**< Current electrical angle during startup */
  int8_t dir;                         /**< Startup rotation direction (1 = forward, -1 = reverse) */
  flag_status closeloop_rdy;          /**< Flag indicating readiness for closed-loop transition */
  flag_status closeloop_rdy_old;      /**< Previous state of closed-loop readiness flag */
  startup_mode_type startup_mode;     /**< Current startup mode (contant current, constant voltage etc.) */
  qd_type* startup_command;           /**< Pointer to q-d axis command values during startup */
} sensorless_startup_type;

/**
 * @brief Initial angle detection structure for FOC sensorless startup
 * 
 * This structure manages the initial rotor angle detection process for sensorless
 * Field-Oriented Control. It implements pulse injection techniques to determine
 * the initial rotor position before starting the motor, ensuring proper startup
 * without position sensors.
 */
typedef struct
{
  tmr_type* ADVTMRx;                  /**< Pointer to advanced timer used for PWM generation */
  tmr_type* ADC_TMRx;                 /**< Pointer to timer used for ADC triggering */
  tmr_channel_select_type ADC_TMRx_CHx; /**< Timer channel selection for ADC triggering */
  uint16_t period;                    /**< PWM period value for pulse injection */
  uint16_t detect_duty;               /**< PWM count value used for pulse injection */
  uint16_t *adc_trig;                 /**< Pointer to ADC trigger position configuration */
  int16_t step_count;                 /**< Step counter for pulse injection sequence */
  int16_t Iap;                        /**< Phase A positive pulse current value */
  int16_t Ian;                        /**< Phase A negative pulse current value */
  int16_t Ibp;                        /**< Phase B positive pulse current value */
  int16_t Ibn;                        /**< Phase B negative pulse current value */
  int16_t Icp;                        /**< Phase C positive pulse current value */
  int16_t Icn;                        /**< Phase C negative pulse current value */
  int16_t init_elec_angle;            /**< Detected initial electrical angle for startup */
} foc_angle_init_type;

/**
 * @brief MOSFET Rds(on) calibration structure for FOC motor control
 * 
 * This structure handles the calibration of MOSFET on-resistance (Rds(on)) for
 * Field-Oriented Control applications, particularly in e-bike and scooter systems.
 * It implements measurement, filtering, and compensation algorithms to account for
 * MOSFET resistance variations due to temperature and manufacturing tolerances.
 */
typedef struct
{
  int32_t P1;                         /**< Raw power measurement value from method 1 */
  int32_t P2;                         /**< Raw power measurement value from method 2 */
  int32_t P1_filt;                    /**< Filtered power measurement value from method 1 */
  int32_t P2_filt;                    /**< Filtered power measurement value from method 2 */
  float P2_Const;                     /**< Calibration constant for power measurement normalization */
  int16_t Perr;                       /**< Differece in power measurements between method 1 and method 2 */
  uint16_t P1_ma_nbr_log;             /**< Moving average window size for power measurement value from method 1 (logarithmic) */
  uint16_t P2_ma_nbr_log;             /**< Moving average window size for power measurement value from method 2 (logarithmic) */
  qd_type *I_val;                     /**< Pointer to q-d axis current measurement values */
  qd_type I_filt_val;                 /**< Filtered q-d axis current values for calibration */
  lowpass_filter_type Iq_LPF;         /**< Low-pass filter for q-axis current filtering */
  lowpass_filter_type Id_LPF;         /**< Low-pass filter for d-axis current filtering */
  int16_t span_upper_limit;           /**< Upper limit for current measurement span */
  int16_t span_lower_limit;           /**< Lower limit for current measurement span */
} rds_cali_type;

/**
  * @brief  USART peripheral configuration structure
  * @details Contains complete hardware configuration parameters for initializing
  *          a USART/UART interface, including clock, GPIO, and baudrate settings.
  *          Supports both standard and remapped pin configurations.
  */
typedef struct
{
  usart_type* usart_x;    /**< @brief USART peripheral pointer */
  uint32_t baudrate;      /**< @brief Communication baud rate (bps) */

  crm_periph_clock_type usart_clock;        /**< @brief USART peripheral clock */
  crm_periph_clock_type usart_tx_gpio_clock; /**< @brief TX GPIO clock */
  crm_periph_clock_type usart_rx_gpio_clock; /**< @brief RX GPIO clock */

  gpio_type* usart_tx_gpio_port;  /**< @brief TX GPIO port pointer */
  uint32_t usart_tx_gpio_pin;     /**< @brief TX pin number */
  gpio_pins_source_type gpio_tx_pin_source; /**< @brief TX pin alternate function */

  gpio_type* usart_rx_gpio_port;  /**< @brief RX GPIO port pointer */
  uint32_t usart_rx_gpio_pin;     /**< @brief RX pin number */
  gpio_pins_source_type gpio_rx_pin_source; /**< @brief RX pin alternate function */

#if !defined AT32F403Axx && !defined AT32F407xx && !defined AT32F413xx && !defined AT32F415xx
  gpio_mux_sel_type gpio_tx_pin_mux; /**< @brief TX pin mux selection */
  gpio_mux_sel_type gpio_rx_pin_mux; /**< @brief RX pin mux selection */
#endif

  uint32_t usart_gpio_remap;      /**< @brief Pin remapping control */
} usart_config_type;

/**
  * @brief  User Interface Waveform Monitoring Structure
  * @details Contains normalized parameters for real-time monitoring and debugging
  *          of motor control variables. All per-unit (pu) values are scaled to
  *          a common range (typically -32768 to +32767 for Q15 format).
  */
typedef struct
{
  int16_t speed_meas_filter_pu;   /**< @brief Filtered speed measurement */
  int16_t speed_reference_pu;     /**< @brief Speed reference/target value */
  int16_t iMosTemperature_meas;   /**< @brief MOSFET temperature measurement (in °C) */
  int16_t iBusVoltage_meas;       /**< @brief DC bus voltage measurement (in volts) */
  int16_t position_meas_pu;       /**< @brief Measured position */
  int16_t position_reference_pu;  /**< @brief Position reference */
  int16_t user_define_a;          /**< @brief User-defined variable A (application-specific) */
  int16_t user_define_b;          /**< @brief User-defined variable B (application-specific) */
  uint8_t sample_cycle;           /**< @brief Application sampling cycle  */
  uint16_t sampling_rate;         /**< @brief Application sampling rate */
} ui_wave_param_type;

/**
 * @brief Current PID auto-tuning structure for motor control
 * 
 * This structure manages the auto-tuning process for current loop PID controllers
 * in Motor Control systems. It automatically calculates optimal PID parameters
 * based on motor electrical characteristics and control requirements.
 */
typedef struct
{
  float *Rs;                         /**< Pointer to stator resistance value (Ω) */
  float *Ls;                         /**< Pointer to stator inductance value (H) */
  double current_base;               /**< Base current value for per-unit conversion */
  double voltage_base;               /**< Base voltage value for per-unit conversion */
  float Vdc_rated;                   /**< Rated DC bus voltage (V) */
  uint16_t Vdc_rated_adc;            /**< Rated DC bus voltage in ADC value */
  uint16_t bandwidth;                /**< Desired control bandwidth (rad/s) */
  uint16_t BW_limit;                 /**< Maximum allowable bandwidth limit (rad/s) */
  int32_t sample_freq;               /**< Controller sampling frequency (Hz) */
  double kp_coff;                    /**< Proportional gain coefficient */
  double ki_coff;                    /**< Integral gain coefficient */
  int16_t kp;                        /**< Calculated proportional gain */
  int16_t ki;                        /**< Calculated integral gain */
  uint16_t kp_shift;                 /**< Bit-shift value for proportional gain fixed-point implementation */
  uint16_t ki_shift;                 /**< Bit-shift value for integral gain fixed-point implementation */
  process_state_type state_flag;     /**< Auto-tuning process state flag */
} i_auto_tune_type;

/**
 * @brief Motor parameter identification type definition
 * 
 * @details This structure contains all the necessary parameters and state variables
 *          for motor parameter identification process, including resistance (Rs)
 *          and inductance (Ls) measurement.
 */
typedef struct
{
  tmr_type* ADVTMRx;                /**< Pointer to advanced timer used for PWM generation */
  int32_t sample_freq;              /**< Sampling frequency for parameter measurement */
  uint16_t pwm_period;              /**< PWM period value */
  int16_t I_nominal;                /**< Nominal current value */
  int16_t I_threshold;              /**< Minimum current threshold for identification */
  int16_t* I_val;                   /**< Pointer to current measurement value */
  float_u32_union Rs;               /**< Stator resistance value (float-uint32 union) */
  float_u32_union Ls;               /**< Stator inductance value (float-uint32 union) */
  float_u32_union Rs_Old;           /**< Previous stator resistance value */
  float_u32_union Ls_Old;           /**< Previous stator inductance value */
  double z_base;                    /**< Base impedance value for calculation */
  uint16_t align_time_count;        /**< Alignment time counter */
  uint8_t count;                    /**< General purpose counter */
  uint16_t duty;                    /**< PWM count value */
  __IO uint16_t* Vbus;              /**< Pointer to bus voltage measurement (volatile) */
  flag_status id_flag;              /**< Identification process status flag */
  process_state_type state_flag;    /**< State machine flag for identification process */
  uint8_t step_flag;                /**< Step indicator for multi-step identification */
  uint16_t timeout;                 /**< Timeout value for identification process */
  uint16_t timeout_count;           /**< Timeout counter */
#ifdef MOTOR_PARAM_IDENTIFY
  int16_t I_Ls_tab[200];            /**< Current measurement table for inductance identification (static array) */
#else
  int16_t *I_Ls_tab;                /**< Pointer to current measurement table for inductance identification (dynamic) */
#endif
} motor_param_id_type;

/**
  * @brief  Hall Sensor Auto-Learning Configuration Structure
  * @details Manages the automatic calibration process for hall sensor alignment
  *          and commutation timing in motor control systems.
  */
typedef struct
{
  hall_learn_process_type process_state; /**< @brief Current state of learning FSM (e.g., INIT, ALIGN, MEASURE) */
  flag_status start_flag;                /**< @brief Process trigger (1=start learning, 0=inactive) */
  flag_status check_flag;                /**< @brief Validation status (1=success, 0=failure) */
  int8_t dir;                            /**< @brief Test rotation direction (0=forward, 1=reverse) */
  int16_t learn_volt;                    /**< @brief Open-loop voltage during hall learning (in Q15) */
  int16_t learn_period;                  /**< @brief Open-loop period during hall learning (in timer ticks) */
  int16_t learn_angle_inc;               /**< @brief Angle increment per step */
  int16_t align_time;                    /**< @brief Alignment phase duration (in microsecond) */
  int16_t count;                         /**< @brief General-purpose cycle counter */
  int16_t step;                          /**< @brief Current learning phase step index */
  hall_sensor_type hall_state;           /**< @brief Hall sensor data and configuration */
} hall_learn_type;

/**
 * @brief Current decoupling control type definition
 * 
 * @details This structure contains parameters and state variables for current decoupling control
 *          in FOC (Field-Oriented Control) algorithm. It implements decoupling terms to compensate
 *          for the cross-coupling between d and q axes.
 */
typedef struct
{
  int32_t const_1d;                 /**< Decoupling constant for d-axis component */
  int32_t const_1q;                 /**< Decoupling constant for q-axis component */
  int32_t const_2;                  /**< Common decoupling constant */
  __IO uint16_t* Vbus;              /**< Pointer to bus voltage measurement (volatile) */
  qd_type Vff;                      /**< Feedforward voltage in qd reference frame */
  lowpass_filter_type Iq_LPF;        /**< Low-pass filter for q-axis current */
  lowpass_filter_type Id_LPF;        /**< Low-pass filter for d-axis current */
} curr_decoupling_type;

/**
 * @brief MTPA/MTPV table data type definition
 * 
 * @details This structure contains the processed data and state information for MTPA/MTPV table operations.
 *          It stores filtered motor data and state flags used during table generation or lookup processes.
 */
typedef struct
{
  int32_t motor_speed_filt;         /**< Filtered motor speed value used for table indexing */
  process_state_type state_flag;    /**< State machine flag indicating current table operation status */
  confirm_state save_flag;          /**< Confirmation flag for data saving/validation operations */
  qd_type I_filt_val;               /**< Filtered current values in qd reference frame for table data */
} mtpa_table_type;

/**
 * @brief MTPA/MTPV table control type definition
 * 
 * @details This structure contains parameters and state variables for Maximum Torque Per Ampere (MTPA)
 *          and Maximum Torque Per Volt (MTPV) table-based control algorithm. It manages the
 *          transition between different operating regions (constant torque and constant power)
 *          and optimizes current references for maximum torque production within voltage and current limits.
 */
typedef struct
{
  mtpa_table_type mtpa_table;       /**< MTPA/MTPV lookup table structure */
  int32_t max_speed;                /**< Maximum operating speed limit for MTPA/MTPV operation */
  int32_t min_speed;                /**< Minimum operating speed limit for MTPA/MTPV operation */
  int16_t inc_speed;                /**< Speed increment step for table interpolation */
  confirm_state check_speed_flag;   /**< Speed verification status and confirmation state */
  uint8_t step_flag;                /**< Step indicator for control state machine progression */
  uint16_t count;                   /**< General purpose counter for timing and state transitions */
  uint16_t timeout;                 /**< Timeout value for control operations and safety */
  uint16_t settle_time;             /**< Settling time allowance for transients and stabilization */
  uint16_t stable_time;             /**< Required stable operation time before state transition */
  lowpass_filter_type Iq_LPF;       /**< Low-pass filter for q-axis current measurement smoothing */
  lowpass_filter_type Id_LPF;       /**< Low-pass filter for d-axis current measurement smoothing */
  qd_type *I_val;                   /**< Pointer to measured current values in qd reference frame */
  ramp_cmd_type *speed_cmd;         /**< Pointer to speed command structure with ramp profile */
  flag_status *btn_flag;            /**< Pointer to external button flag for manual control input */
  int16_t speed_tolerance;          /**< Allowable speed tolerance range for stable operation */
  int16_t Id_inc;                   /**< d-axis current increment step size for table search */
  int16_t Id_dec;                   /**< d-axis current decrement step size for table search */
} mtpa_type;

/**
  * @brief  Remote control PWM input structure
  * @details Maps PWM pulse width to motor speed with adjustable speed curves
  */
typedef struct
{
  calibrate_process_type state;      /**< Calibration state machine */
  int16_t zero_bw_cval;              /**< Neutral PWM cval (motor stop) */
  int16_t max_bw_cval;               /**< Max PWM cval (full speed forward) */
  int16_t min_bw_cval;               /**< Min PWM cval (full speed reverse) */
  int16_t low_spd_gain;              /**< Low speed range multiplier */
  int16_t high_spd_gain_cw;          /**< High speed multiplier (forward) */
  int16_t high_spd_gain_ccw;         /**< High speed multiplier (reverse) */
  int16_t max_speed;                 /**< Maximum motor speed (forward) */
  int16_t min_speed;                 /**< Maximum motor speed (reverse) */
  int8_t dir;                        /**< Rotation direction (1=forward, -1=reverse) */
} pwm_in_type;

/**
  * @brief  Sound control structure
  * @details Controls tone generation for motor output
  */
typedef struct
{
  uint16_t frequency;  /**< Tone frequency in Hz */
  uint16_t amplitude;  /**< Volume level (0=off, max=full volume) */
  uint16_t period;     /**< Duration in milliseconds (0=continuous) */
} sound_type;

/**
 * @brief Three-phase ADC channel selection structure
 * 
 * @details This structure contains ADC channel selections for three-phase current measurement.
 *          It is used to configure which ADC channels are assigned to measure each phase current
 *          in a three-phase system, typically for motor control applications.
 */
typedef struct
{
  adc_channel_select_type ph_a;     /**< ADC channel selection for phase A current measurement */
  adc_channel_select_type ph_b;     /**< ADC channel selection for phase B current measurement */
  adc_channel_select_type ph_c;     /**< ADC channel selection for phase C current measurement */
} three_phase_adc_channel;

/**
  * @brief  BEMF zero-crossing blanking control structure
  * @details Configures noise filtering for comparator-based zero-cross detection
  */
typedef struct
{
  tmr_type* TMRx;                 /**< Timer instance for blanking control */
  tmr_channel_select_type TMR_CH; /**< Timer channel used for blanking */
  int16_t blank_window_dt[2];     /**< Blanking window counter(timer ticks) */
} blank_type;

/**
  * @brief  Blanking window trigger configuration structure
  * @details Configures timer for generating blanking window trigger signals
  *          to mask noise during PWM switching transitions
  */
typedef struct
{
  tmr_type* TMRx;          /**< Timer instance used for blanking trigger generation */
  int16_t sample_point[2]; /**< Trigger timing points [rising_edge, falling_edge] (in timer ticks) */
} blank_trigger_type;

#ifdef __cplusplus
}
#endif

#endif

